# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_USER=bazar
      - MYSQL_PASSWORD=bazar_pass
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 3003:8080
volumes:
  db:
    driver: local
